// src/components/cv/candidate/shared/countriesData.js
// Canonical country → nationality (demonym) map.
// Names are in English and match the spellings used elsewhere in the app.

export const COUNTRY_TO_NATIONALITY = {
  Afghanistan: "Afghan",
  Albania: "Albanian",
  Algeria: "Algerian",
  Andorra: "Andorran",
  Angola: "Angolan",
  "Antigua and Barbuda": "Antiguan and Barbudan",
  Argentina: "Argentinian",
  Armenia: "Armenian",
  Australia: "Australian",
  Austria: "Austrian",
  Azerbaijan: "Azerbaijani",
  Bahamas: "Bahamian",
  Bahrain: "Bahraini",
  Bangladesh: "Bangladeshi",
  Barbados: "Barbadian",
  Belarus: "Belarusian",
  Belgium: "Belgian",
  Belize: "Belizean",
  Benin: "Beninese",
  Bhutan: "Bhutanese",
  Bolivia: "Bolivian",
  "Bosnia and Herzegovina": "Bosnian",
  Botswana: "Botswanan",
  Brazil: "Brazilian",
  Brunei: "Bruneian",
  Bulgaria: "Bulgarian",
  "Burkina Faso": "Burkinabe",
  Burundi: "Burundian",
  Cambodia: "Cambodian",
  Cameroon: "Cameroonian",
  Canada: "Canadian",
  "Cape Verde": "Cape Verdean",
  "Central African Republic": "Central African",
  Chad: "Chadian",
  Chile: "Chilean",
  China: "Chinese",
  Colombia: "Colombian",
  Comoros: "Comorian",
  "Congo, Democratic Republic of the": "Congolese (DRC)",
  "Congo, Republic of the": "Congolese",
  "Costa Rica": "Costa Rican",
  "Cote d'Ivoire": "Ivorian",
  Croatia: "Croatian",
  Cuba: "Cuban",
  Cyprus: "Cypriot",
  "Czech Republic": "Czech",
  Denmark: "Danish",
  Djibouti: "Djiboutian",
  Dominica: "Dominican",
  "Dominican Republic": "Dominican",
  Ecuador: "Ecuadorian",
  Egypt: "Egyptian",
  "El Salvador": "Salvadoran",
  "Equatorial Guinea": "Equatorial Guinean",
  Eritrea: "Eritrean",
  Estonia: "Estonian",
  Eswatini: "Swazi",
  Ethiopia: "Ethiopian",
  Fiji: "Fijian",
  Finland: "Finnish",
  France: "French",
  Gabon: "Gabonese",
  Gambia: "Gambian",
  Georgia: "Georgian",
  Germany: "German",
  Ghana: "Ghanaian",
  Greece: "Greek",
  Grenada: "Grenadian",
  Guatemala: "Guatemalan",
  Guinea: "Guinean",
  "Guinea-Bissau": "Bissau-Guinean",
  Guyana: "Guyanese",
  Haiti: "Haitian",
  Honduras: "Honduran",
  Hungary: "Hungarian",
  Iceland: "Icelandic",
  India: "Indian",
  Indonesia: "Indonesian",
  Iran: "Iranian",
  Iraq: "Iraqi",
  Ireland: "Irish",
  Israel: "Israeli",
  Italy: "Italian",
  Jamaica: "Jamaican",
  Japan: "Japanese",
  Jordan: "Jordanian",
  Kazakhstan: "Kazakhstani",
  Kenya: "Kenyan",
  Kiribati: "I-Kiribati",
  Kosovo: "Kosovar",
  Kuwait: "Kuwaiti",
  Kyrgyzstan: "Kyrgyz",
  Laos: "Laotian",
  Latvia: "Latvian",
  Lebanon: "Lebanese",
  Lesotho: "Basotho",
  Liberia: "Liberian",
  Libya: "Libyan",
  Liechtenstein: "Liechtensteiner",
  Lithuania: "Lithuanian",
  Luxembourg: "Luxembourger",
  Madagascar: "Malagasy",
  Malawi: "Malawian",
  Malaysia: "Malaysian",
  Maldives: "Maldivian",
  Mali: "Malian",
  Malta: "Maltese",
  "Marshall Islands": "Marshallese",
  Mauritania: "Mauritanian",
  Mauritius: "Mauritian",
  Mexico: "Mexican",
  Micronesia: "Micronesian",
  Moldova: "Moldovan",
  Monaco: "Monegasque",
  Mongolia: "Mongolian",
  Montenegro: "Montenegrin",
  Morocco: "Moroccan",
  Mozambique: "Mozambican",
  Myanmar: "Burmese",
  Namibia: "Namibian",
  Nauru: "Nauruan",
  Nepal: "Nepalese",
  Netherlands: "Dutch",
  "New Zealand": "New Zealander",
  Nicaragua: "Nicaraguan",
  Niger: "Nigerien",
  Nigeria: "Nigerian",
  "North Korea": "North Korean",
  "North Macedonia": "Macedonian",
  Norway: "Norwegian",
  Oman: "Omani",
  Pakistan: "Pakistani",
  Palau: "Palauan",
  Palestine: "Palestinian",
  Panama: "Panamanian",
  "Papua New Guinea": "Papua New Guinean",
  Paraguay: "Paraguayan",
  Peru: "Peruvian",
  Philippines: "Filipino",
  Poland: "Polish",
  Portugal: "Portuguese",
  "Puerto Rico": "Puerto Rican",
  Qatar: "Qatari",
  Romania: "Romanian",
  Russia: "Russian",
  Rwanda: "Rwandan",
  "Saint Kitts and Nevis": "Kittitian/Nevisian",
  "Saint Lucia": "Saint Lucian",
  "Saint Vincent and the Grenadines": "Vincentian",
  Samoa: "Samoan",
  "San Marino": "Sammarinese",
  "Sao Tome and Principe": "Sao Tomean",
  "Saudi Arabia": "Saudi",
  Senegal: "Senegalese",
  Serbia: "Serbian",
  Seychelles: "Seychellois",
  "Sierra Leone": "Sierra Leonean",
  Singapore: "Singaporean",
  Slovakia: "Slovak",
  Slovenia: "Slovenian",
  "Solomon Islands": "Solomon Islander",
  Somalia: "Somali",
  "South Africa": "South African",
  "South Korea": "South Korean",
  "South Sudan": "South Sudanese",
  Spain: "Spanish",
  "Sri Lanka": "Sri Lankan",
  Sudan: "Sudanese",
  Suriname: "Surinamese",
  Sweden: "Swedish",
  Switzerland: "Swiss",
  Syria: "Syrian",
  Taiwan: "Taiwanese",
  Tajikistan: "Tajik",
  Tanzania: "Tanzanian",
  Thailand: "Thai",
  "Timor-Leste": "Timorese",
  Togo: "Togolese",
  Tonga: "Tongan",
  "Trinidad and Tobago": "Trinidadian/Tobagonian",
  Tunisia: "Tunisian",
  Turkey: "Turkish",
  Turkmenistan: "Turkmen",
  Tuvalu: "Tuvaluan",
  Uganda: "Ugandan",
  Ukraine: "Ukrainian",
  "United Arab Emirates": "Emirati",
  "United Kingdom": "British",
  "United States": "American",
  Uruguay: "Uruguayan",
  Uzbekistan: "Uzbek",
  Vanuatu: "Ni-Vanuatu",
  "Vatican City": "Vatican",
  Venezuela: "Venezuelan",
  Vietnam: "Vietnamese",
  Yemen: "Yemeni",
  Zambia: "Zambian",
  Zimbabwe: "Zimbabwean",
};

// Convenience arrays (kept for backwards compatibility with existing imports)
export const COUNTRIES = Object.keys(COUNTRY_TO_NATIONALITY);
// Dedup demonyms so React option keys are unique
export const NATIONALITIES = Array.from(
  new Set(COUNTRIES.map((c) => COUNTRY_TO_NATIONALITY[c]))
);
