// src/components/cv/candidate/shared/rankData.js
export const DEPARTMENTS = ["Deck", "Engine", "Interior", "Galley", "Other"];

export const RANKS_BY_DEPT = {
  Deck: [
    "Captain",
    "Relief Captain",
    "Captain/Engineer",
    "Skipper",
    "Chase Boat Captain",
    "Chief Officer",
    "2nd Officer",
    "3rd Officer",
    "Mate",
    "Mate/Engineer",
    "Mate/Steward(ess)",
    "Bosun",
    "Lead Deckhand",
    "Deckhand",
    "Deck/Engineer",
    "Deck/Steward(ess)",
    "Deck/Carpenter",
    "Deck/Divemaster",
    "Deck/Personal Trainer",
    "Deck/Cook",
  ],
  Engine: [
    "Chief Engineer",
    "2nd Engineer",
    "3rd Engineer",
    "Solo Engineer",
    "Engineer",
    "Electrician",
  ],
  Galley: [
    "Chef",
    "Head Chef",
    "Sous Chef",
    "Solo Chef",
    "Cook",
    "Cook/Crew Chef",
    "Crew Chef/Stew",
    "Chef/Steward(ess)",
    "Cook/Steward(ess)",
  ],
  Interior: [
    "Steward(ess)",
    "Chief Steward(ess)",
    "2nd Steward(ess)",
    "3rd Steward(ess)",
    "4th Steward(ess)",
    "Solo Steward(ess)",
    "Junior Steward(ess)",
    "Laundry/Steward(ess)",
    "Butler",
    "Head of Housekeeping",
    "Housekeeper",
    "Stew/Deck",
    "Stew/Masseur",
    "Stew/Yoga Instructor",
    "Steward(ess)/Nanny",
    "Chef/Stew/Deck",
    "Cook/Stew/Deck",
  ],
  Other: [
    "Dayworker",
    "Nurse",
    "Dive Instructor",
    "Water Sport Instructor",
    "Masseur",
    "Hairdresser/Barber",
    "Nanny",
    "Yoga/Pilates Instructor",
    "Personal Trainer",
    "Videographer",
    "Other",
  ],
};

export function getRanksForDept(dept) {
  return RANKS_BY_DEPT[dept] || [];
}
