-- Fix yacht_work_offers_teammate_rank_check to match current rank list and allow NULL
-- Error: new row for relation "yacht_work_offers" violates check constraint "yacht_work_offers_teammate_rank_check"
ALTER TABLE public.yacht_work_offers
  DROP CONSTRAINT IF EXISTS yacht_work_offers_teammate_rank_check;

ALTER TABLE public.yacht_work_offers
  ADD CONSTRAINT yacht_work_offers_teammate_rank_check
  CHECK (
    teammate_rank IS NULL OR teammate_rank = ANY (ARRAY[
      'Captain',
      'Relief Captain',
      'Captain/Engineer',
      'Skipper',
      'Chase Boat Captain',
      'Chief Officer',
      '2nd Officer',
      '3rd Officer',
      'Mate',
      'Mate/Engineer',
      'Mate/Steward(ess)',
      'Bosun',
      'Lead Deckhand',
      'Deckhand',
      'Deck/Engineer',
      'Deck/Steward(ess)',
      'Deck/Carpenter',
      'Deck/Divemaster',
      'Deck/Personal Trainer',
      'Deck/Cook',
      'Chief Engineer',
      '2nd Engineer',
      '3rd Engineer',
      'Solo Engineer',
      'Engineer',
      'Electrician',
      'Chef',
      'Head Chef',
      'Sous Chef',
      'Solo Chef',
      'Cook',
      'Cook/Crew Chef',
      'Crew Chef/Stew',
      'Chef/Steward(ess)',
      'Cook/Steward(ess)',
      'Steward(ess)',
      'Chief Steward(ess)',
      '2nd Steward(ess)',
      '3rd Steward(ess)',
      '4th Steward(ess)',
      'Solo Steward(ess)',
      'Junior Steward(ess)',
      'Laundry/Steward(ess)',
      'Butler',
      'Head of Housekeeping',
      'Housekeeper',
      'Stew/Deck',
      'Stew/Masseur',
      'Stew/Yoga Instructor',
      'Steward(ess)/Nanny',
      'Chef/Stew/Deck',
      'Cook/Stew/Deck',
      'Dayworker',
      'Nurse',
      'Dive Instructor',
      'Water Sport Instructor',
      'Masseur',
      'Hairdresser/Barber',
      'Nanny',
      'Yoga/Pilates Instructor',
      'Personal Trainer',
      'Videographer',
      'Other'
    ]))
  );
